language: php

php:
  - '7.0'

env:
  global:
    - CODECLIMATE_REPO_TOKEN: abcf79de4e15af53a064642428a4bbba85e940d02cb2946181f2cc7b69f68feb

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - composer install --no-interaction --no-progress

script: php vendor/bin/phpunit -v -c phpunit.xml.dist

after_success:
  - travis_retry php vendor/bin/coveralls
  - travis_retry php vendor/bin/test-reporter

notifications:
  email: true

addons:
    code_climate:
        repo_token: abcf79de4e15af53a064642428a4bbba85e940d02cb2946181f2cc7b69f68feb